import { useEffect, useState } from "react";
import {
  ResponsiveContainer, ComposedChart, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend,
} from "recharts";
import { TopBar } from "../components/layout/TopBar";
import { LoadingState, ErrorState, EmptyState } from "../components/ui/States";
import { useFilters } from "../state/FiltersContext";
import { getForecast } from "../services/forecastApi";
import { getInventory } from "../services/inventoryApi";
import type { ForecastResult } from "../types";
import { Cpu } from "lucide-react";

export default function Forecast() {
  const { filters } = useFilters();
  const [partOptions, setPartOptions] = useState<string[]>([]);
  const [part, setPart] = useState("");
  const [result, setResult] = useState<ForecastResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getInventory().then((inv) => {
      if (inv.length > 0) {
        const unique = Array.from(new Set(inv.map((i) => i.part)));
        setPartOptions(unique);
        setPart(unique[0]);
      } else {
        setPartOptions([]);
        setPart("");
        setResult(null);
        setLoading(false);
      }
    });
  }, []);

  const load = () => {
    if (!part) {
      setLoading(false);
      setResult(null);
      return;
    }
    setLoading(true);
    setError(null);
    getForecast({
      part,
      start_date: filters.startDate,
      end_date: filters.endDate,
      horizon: filters.horizon,
    })
      .then(setResult)
      .catch(() => setError("The forecasting service could not be reached."))
      .finally(() => setLoading(false));
  };

  useEffect(load, [filters.startDate, filters.endDate, filters.horizon, part]); // eslint-disable-line react-hooks/exhaustive-deps

  // Map series data to include confidence range tuple for Recharts Area range plotting
  const chartData = result?.series.map((item) => ({
    ...item,
    confidenceRange:
      item.lowerBound !== undefined && item.upperBound !== undefined
        ? [item.lowerBound, item.upperBound]
        : undefined,
  })) || [];

  return (
    <div>
      <TopBar title="Demand Forecast" subtitle="What will we need? — ML demand forecasting" />

      <div className="p-6 space-y-4">
        {/* ML MODEL EXPLICIT BANNER */}
        <div className="flex items-center justify-between rounded-md border border-[--color-forecast-500]/30 bg-[--color-forecast-500]/10 px-4 py-3 text-sm">
          <div className="flex items-center gap-2.5">
            <Cpu className="text-[--color-forecast-600]" size={18} />
            <div>
              <p className="font-semibold text-[--color-ink-900]">External ML Forecasting Engine Integration</p>
              <p className="text-xs text-[--color-ink-600]">
                Forecasts are generated by your external Machine Learning model and rendered here for operational decision-making.
              </p>
            </div>
          </div>
          <span className="rounded-full bg-[--color-forecast-500]/20 px-2.5 py-1 text-xs font-medium text-[--color-forecast-700]">
            Forecast generated by the ML model
          </span>
        </div>

        {/* INPUT CONTROLS */}
        <div className="flex flex-wrap items-center justify-between gap-4 rounded-md border border-[--color-border] bg-[--color-surface-0] p-4">
          <div className="flex items-center gap-3">
            <label className="text-xs font-semibold uppercase tracking-wider text-[--color-ink-500]">Select Part / Item</label>
            <select
              value={part}
              disabled={partOptions.length === 0}
              onChange={(e) => setPart(e.target.value)}
              className="rounded border border-[--color-border] bg-[--color-surface-0] px-3 py-1.5 text-sm font-medium text-[--color-ink-900] disabled:opacity-50"
            >
              {partOptions.length === 0 ? (
                <option value="">No Inventory Items</option>
              ) : (
                partOptions.map((p) => (
                  <option key={p} value={p}>{p}</option>
                ))
              )}
            </select>
          </div>

          <div className="text-xs text-[--color-ink-500]">
            Horizon: <span className="font-semibold text-[--color-forecast-600]">{filters.horizon} Months</span>
          </div>
        </div>

        {loading ? (
          <LoadingState label="Requesting forecast parameters from the ML service…" />
        ) : error ? (
          <ErrorState title="Forecasting model unavailable." message={error} onRetry={load} />
        ) : !part || !result || result.series.length === 0 ? (
          <EmptyState
            title="No inventory items available for demand forecasting"
            message="Add parts to Inventory to calculate demand forecasts with the external ML model."
          />
        ) : (<>
            {/* MODEL EVALUATION METRICS */}
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
              {[
                { label: "ML Model Name", value: result.modelName },
                { label: "MAE (Mean Abs Error)", value: result.mae.toFixed(1) },
                { label: "RMSE (Root Mean Sq)", value: result.rmse.toFixed(1) },
                { label: "MAPE (Error %)", value: `${result.mape.toFixed(1)}%` },
                { label: "Model Bias", value: result.bias.toFixed(1) },
              ].map((m) => (
                <div key={m.label} className="rounded-md border border-[--color-border] bg-[--color-surface-0] p-3">
                  <p className="text-[10px] uppercase tracking-wide text-[--color-ink-500]">{m.label}</p>
                  <p className="tabular mt-1 text-sm font-semibold text-[--color-ink-900]">{m.value}</p>
                </div>
              ))}
            </div>

            {/* DEMAND FORECAST CHART & BAND */}
            <div className="rounded-md border border-[--color-border] bg-[--color-surface-0] p-4">
              <div className="mb-3 flex items-center justify-between">
                <p className="text-sm font-semibold text-[--color-ink-900]">
                  {part} — Historical Demand vs. ML Demand Forecast
                </p>
                <p className="text-xs text-[--color-ink-500]">
                  Includes 95% ML Confidence Interval Band
                </p>
              </div>

              <ResponsiveContainer width="100%" height={340}>
                <ComposedChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                  <XAxis dataKey="period" tick={{ fontSize: 12 }} stroke="var(--color-ink-400)" />
                  <YAxis tick={{ fontSize: 12 }} stroke="var(--color-ink-400)" />
                  <Tooltip />
                  <Legend />
                  <Area
                    type="monotone"
                    dataKey="confidenceRange"
                    stroke="none"
                    fill="var(--color-forecast-500)"
                    fillOpacity={0.2}
                    name="95% Confidence Band"
                  />
                  <Line type="monotone" dataKey="actual" stroke="var(--color-ink-700)" strokeWidth={2} dot={false} name="Historical Demand" />
                  <Line
                    type="monotone"
                    dataKey="forecast"
                    stroke="var(--color-forecast-500)"
                    strokeWidth={2}
                    strokeDasharray="4 3"
                    dot={false}
                    name="ML Forecast Demand"
                  />
                </ComposedChart>
              </ResponsiveContainer>
            </div>

            {/* FORECAST DATA TABLE */}
            <div className="overflow-hidden rounded-md border border-[--color-border] bg-[--color-surface-0]">
              <div className="border-b border-[--color-border] px-4 py-2.5 text-xs font-semibold uppercase tracking-wider text-[--color-ink-500]">
                ML Forecast Breakdown Table
              </div>
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-[--color-border] text-left uppercase text-[--color-ink-500]">
                    <th className="px-4 py-2">Period</th>
                    <th className="px-2 py-2">Historical Demand</th>
                    <th className="px-2 py-2">ML Forecast</th>
                    <th className="px-2 py-2">Lower Bound</th>
                    <th className="px-2 py-2">Upper Bound</th>
                  </tr>
                </thead>
                <tbody>
                  {result.series.map((point) => (
                    <tr key={point.period} className="border-b border-[--color-border] last:border-0 hover:bg-[--color-surface-1]">
                      <td className="px-4 py-2 font-medium text-[--color-ink-900]">{point.period}</td>
                      <td className="tabular px-2 py-2">{point.actual !== undefined ? point.actual : "—"}</td>
                      <td className="tabular px-2 py-2 font-semibold text-[--color-forecast-600]">{point.forecast !== undefined ? point.forecast : "—"}</td>
                      <td className="tabular px-2 py-2 text-[--color-ink-500]">{point.lowerBound !== undefined ? point.lowerBound : "—"}</td>
                      <td className="tabular px-2 py-2 text-[--color-ink-500]">{point.upperBound !== undefined ? point.upperBound : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
