import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Play, Calculator, ArrowRight, CheckSquare } from "lucide-react";
import { TopBar } from "../components/layout/TopBar";
import { LoadingState, ErrorState, EmptyState } from "../components/ui/States";
import { StatusBadge } from "../components/ui/StatusBadge";
import { useFilters } from "../state/FiltersContext";
import { runOptimization } from "../services/procurementApi";
import type { ProcurementResult } from "../types";

export default function Procurement() {
  const { filters } = useFilters();
  const navigate = useNavigate();

  const [budget, setBudget] = useState(0);
  const [serviceLevel, setServiceLevel] = useState(0.95);
  const [result, setResult] = useState<ProcurementResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<number>>(new Set());

  const run = () => {
    setLoading(true);
    setError(null);
    runOptimization({
      budget,
      forecast_horizon: filters.horizon,
      service_level: serviceLevel,
    })
      .then((r) => {
        setResult(r);
        setSelected(new Set(r.items.map((_, i) => i)));
      })
      .catch(() => setError("The optimization service could not be reached."))
      .finally(() => setLoading(false));
  };

  const createPO = () => {
    if (!result) return;
    const items = result.items.filter((_, i) => selected.has(i));
    navigate("/purchase-orders/new", { state: { items } });
  };

  return (
    <div>
      <TopBar title="Procurement Optimization" subtitle="What should we buy? — PuLP mathematical optimization model" />

      <div className="p-4 sm:p-6 space-y-4">
        {/* PuLP MODEL EXPLICIT BANNER */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 rounded-md border border-[--color-optimize-500]/30 bg-[--color-optimize-500]/10 px-4 py-3 text-sm">
          <div className="flex items-center gap-2.5">
            <Calculator className="text-[--color-optimize-600] shrink-0" size={18} />
            <div>
              <p className="font-semibold text-[--color-ink-900]">PuLP Mathematical Optimization Integration</p>
              <p className="text-xs text-[--color-ink-600]">
                Purchase quantities are computed by your external PuLP optimization backend to balance budget, demand forecasts, and stockout risk.
              </p>
            </div>
          </div>
          <span className="shrink-0 rounded-full bg-[--color-optimize-500]/20 px-2.5 py-1 text-xs font-medium text-[--color-optimize-700]">
            Recommendations generated by the PuLP optimization model
          </span>
        </div>

        {/* PARAMETER INPUTS */}
        <div className="rounded-md border border-[--color-border] bg-[--color-surface-0] p-4">
          <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-[--color-ink-500]">Optimization Input Parameters</p>
          <div className="flex flex-col sm:flex-row sm:items-end flex-wrap gap-3 sm:gap-4">
            <div className="w-full sm:w-auto">
              <label className="mb-1 block text-xs text-[--color-ink-500]">Forecast Horizon</label>
              <div className="rounded border border-[--color-border] bg-[--color-surface-1] px-2.5 py-1.5 text-sm text-[--color-ink-700]">
                {filters.horizon} Months (top bar)
              </div>
            </div>

            <div className="w-full sm:w-auto">
              <label className="mb-1 block text-xs text-[--color-ink-500]">Available Budget (₹)</label>
              <input
                type="number"
                step="10000"
                value={budget}
                onChange={(e) => setBudget(Number(e.target.value))}
                className="w-full sm:w-40 rounded border border-[--color-border] px-2.5 py-1.5 text-sm tabular font-semibold"
              />
            </div>

            <div className="w-full sm:w-auto">
              <label className="mb-1 block text-xs text-[--color-ink-500]">Target Service Level</label>
              <select
                value={serviceLevel}
                onChange={(e) => setServiceLevel(Number(e.target.value))}
                className="w-full sm:w-auto rounded border border-[--color-border] px-2.5 py-1.5 text-sm"
              >
                {[0.9, 0.95, 0.98, 0.99].map((s) => (
                  <option key={s} value={s}>{(s * 100).toFixed(0)}% Service Level</option>
                ))}
              </select>
            </div>

            <button
              onClick={run}
              className="w-full sm:w-auto flex items-center justify-center gap-1.5 rounded bg-[--color-optimize-500] px-4 py-1.5 text-sm font-medium text-white hover:bg-[--color-optimize-700] active:scale-98 transition-all"
            >
              <Play size={14} /> Run PuLP Optimizer
            </button>
          </div>
        </div>

        {/* RESULTS SECTION */}
        <div>
          {loading ? (
            <LoadingState label="Submitting budget constraints to PuLP optimization service…" />
          ) : error ? (
            <ErrorState
              title="Optimization service unavailable."
              message="Could not connect to external PuLP backend."
              onRetry={run}
            />
          ) : !result ? (
            <EmptyState title="No optimization run executed yet" message="Set your budget and service level target, then click Run PuLP Optimizer." />
          ) : result.items.length === 0 ? (
            <EmptyState
              title="No procurement recommendations generated"
              message="No inventory items currently require reordering based on safety stock thresholds and stockout risks."
            />
          ) : (
            <div className="rounded-md border border-[--color-border] bg-[--color-surface-0]">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[--color-border] px-4 py-3">
                <div className="flex flex-wrap gap-4 sm:gap-6 text-sm">
                  <div>
                    <p className="text-[11px] text-[--color-ink-500] uppercase tracking-wide">Total Budget</p>
                    <p className="tabular font-semibold text-[--color-ink-900]">₹{result.budget.toLocaleString("en-IN")}</p>
                  </div>
                  <div>
                    <p className="text-[11px] text-[--color-ink-500] uppercase tracking-wide">Recommended Spend</p>
                    <p className="tabular font-semibold text-[--color-optimize-700]">₹{result.recommended_spend.toLocaleString("en-IN")}</p>
                  </div>
                  <div>
                    <p className="text-[11px] text-[--color-ink-500] uppercase tracking-wide">Unallocated Budget</p>
                    <p className="tabular font-semibold text-[--color-ink-700]">₹{result.remaining_budget.toLocaleString("en-IN")}</p>
                  </div>
                </div>

                <button
                  onClick={createPO}
                  disabled={selected.size === 0}
                  className="flex items-center justify-center gap-2 rounded bg-[--color-forecast-500] px-4 py-2 text-sm font-medium text-white hover:bg-[--color-forecast-700] disabled:opacity-40 w-full sm:w-auto"
                >
                  <CheckSquare size={16} /> Create Purchase Order ({selected.size} items) <ArrowRight size={14} />
                </button>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-sm min-w-[650px]">
                  <thead>
                    <tr className="border-b border-[--color-border] text-left text-xs uppercase tracking-wide text-[--color-ink-500]">
                      <th className="w-8 px-4 py-2.5"></th>
                      <th className="px-2 py-2.5">Recommended Part</th>
                      <th className="px-2 py-2.5">PuLP Qty</th>
                      <th className="px-2 py-2.5">Unit Price</th>
                      <th className="px-2 py-2.5">Total Cost</th>
                      <th className="px-2 py-2.5">Recommended Supplier</th>
                      <th className="px-2 py-2.5">Priority</th>
                    </tr>
                  </thead>
                  <tbody>
                    {result.items.map((item, i) => (
                      <tr key={item.part} className="border-b border-[--color-border] last:border-0 hover:bg-[--color-surface-1]">
                        <td className="px-4 py-2.5">
                          <input
                            type="checkbox"
                            checked={selected.has(i)}
                            onChange={() =>
                              setSelected((s) => {
                                const next = new Set(s);
                                next.has(i) ? next.delete(i) : next.add(i);
                                return next;
                              })
                            }
                          />
                        </td>
                        <td className="px-2 py-2.5 font-medium text-[--color-ink-900]">{item.part}</td>
                        <td className="tabular px-2 py-2.5 font-bold text-[--color-optimize-700]">{item.quantity}</td>
                        <td className="tabular px-2 py-2.5">₹{item.unit_price.toLocaleString("en-IN")}</td>
                        <td className="tabular px-2 py-2.5 font-semibold">₹{item.total_cost.toLocaleString("en-IN")}</td>
                        <td className="px-2 py-2.5 text-[--color-ink-700]">{item.supplier}</td>
                        <td className="px-2 py-2.5">
                          <StatusBadge label={item.priority} />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
