const SYSTEM_INSTRUCTION = `Role: Specialized Fleet & Supply Chain Assistant for Kerala State Road Transport Corporation (KSRTC).

STRICT OUTPUT RULES:
1. Immediately answer the user query with operational facts, figures, analysis, or steps.
2. Under NO circumstance should you start messages with an introduction, boilerplate greeting, or identity statement. Never write sentences like "I am...", "This is...", or "As KSRTC SCION...".
3. Jump directly to the technical response.
4. Only describe your identity if the user explicitly asks "Who are you?" or "What is your identity?".
5. Numbered lists MUST always be strictly sequential (1., 2., 3., 4...). Never repeat or reset numbering back to 1. for subsequent items.
6. Maintain domain expertise in KSRTC bus fleet spare parts (braking, suspension, engine, transmission), depot inventory management, Economic Order Quantity (EOQ), reorder levels, safety stock thresholds, and purchase orders.`;

const INTERACTIONS_ENDPOINT = "https://generativelanguage.googleapis.com/v1/interactions";
const MODEL_NAME = "gemini-3.5-flash-lite";

/**
 * Extracts assistant response text from Google Interactions API response structure.
 */
function extractInteractionText(data: any): string {
  if (!data) return "";

  // 1. Interactions API standard: steps -> model_output -> content -> text
  if (Array.isArray(data.steps)) {
    const modelOutputSteps = data.steps.filter((s: any) => s && s.type === "model_output");
    const targetSteps = modelOutputSteps.length > 0 ? modelOutputSteps : data.steps;

    const texts: string[] = [];
    for (const step of targetSteps) {
      if (Array.isArray(step.content)) {
        for (const item of step.content) {
          if (item && typeof item.text === "string" && item.text.trim()) {
            texts.push(item.text);
          }
        }
      } else if (typeof step.content === "string" && step.content.trim()) {
        texts.push(step.content);
      } else if (typeof step.text === "string" && step.text.trim()) {
        texts.push(step.text);
      }
    }

    if (texts.length > 0) {
      return texts.join("\n\n").trim();
    }
  }

  // 2. Direct text property
  if (typeof data.text === "string" && data.text.trim()) {
    return data.text.trim();
  }

  // 3. Outputs array format
  if (Array.isArray(data.outputs)) {
    const texts = data.outputs
      .map((o: any) => (typeof o === "string" ? o : o?.text || o?.content || ""))
      .filter(Boolean);
    if (texts.length > 0) return texts.join("\n\n").trim();
  }

  // 4. Candidates array fallback
  if (Array.isArray(data.candidates) && data.candidates[0]?.content?.parts) {
    const parts = data.candidates[0].content.parts
      .map((p: any) => p.text || "")
      .filter(Boolean);
    if (parts.length > 0) return parts.join("\n\n").trim();
  }

  return "";
}

/**
 * Calls Google's Interactions API endpoint (POST /v1/interactions) using gemini-3.5-flash-lite.
 */
async function callInteractionsApi(
  apiKey: string,
  prompt: string,
  systemInstruction: string
): Promise<{ text?: string; error?: string }> {
  const url = `${INTERACTIONS_ENDPOINT}?key=${encodeURIComponent(apiKey)}`;

  const payload = {
    model: MODEL_NAME,
    input: prompt,
    system_instruction: systemInstruction,
  };

  const maxAttempts = 2;
  let lastError = "";

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const response = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const responseData = (await response.json().catch(() => null)) as any;

      if (response.ok && responseData) {
        const generatedText = extractInteractionText(responseData);
        if (generatedText) {
          return { text: generatedText };
        }
        return { text: "No response text generated by KSRTC SCION." };
      }

      const errorMessage =
        responseData?.error?.message ||
        `Interactions API request failed with status ${response.status} (${response.statusText})`;

      // If high demand (503), retry once after a short delay
      if (response.status === 503 && attempt < maxAttempts) {
        console.warn(`[SCION AI] Attempt ${attempt} received 503 high demand, retrying in 1.5s...`);
        await new Promise((resolve) => setTimeout(resolve, 1500));
        continue;
      }

      // If rate limited (429), return a clear explanatory message
      if (response.status === 429) {
        return {
          error: `Google Gemini Rate Limit: ${errorMessage}`,
        };
      }

      lastError = errorMessage;
      break;
    } catch (networkErr: any) {
      lastError = `Network connection error reaching Google Interactions API: ${networkErr?.message || networkErr}`;
      if (attempt < maxAttempts) {
        await new Promise((resolve) => setTimeout(resolve, 1500));
      }
    }
  }

  return { error: lastError || "Failed to communicate with KSRTC SCION." };
}

/**
 * Removes repetitive boilerplate introduction ("I am KSRTC SCION...") when not answering an identity question.
 */
export function sanitizeResponseText(text: string, userQuery: string = ""): string {
  if (!text) return "";
  const isAskingIdentity = /\b(who are you|what is your name|identify yourself|what are you)\b/i.test(userQuery);
  if (isAskingIdentity) {
    return text.trim();
  }

  let cleaned = text.trim();

  // 1. Strip leading greetings and self-intro lines regardless of markdown formatting
  cleaned = cleaned.replace(
    /^(\s*[*#_>`"'-]*\s*(?:(?:Hello|Hi|Greetings|Welcome)[^.\n]*[.,!?:;\n]+)?\s*[*#_>`"'-]*\s*(?:I am|I'm|This is|As)\s+(?:the\s+)?(?:KSRTC\s+SCION|SCION|Kerala State Road Transport Corporation)[^\n]*?(?:[.:!\n]|\s*\n)\s*[*#_>`"'-]*\s*)+/i,
    ""
  );

  // 2. Strip any exact standalone line matching the specific boilerplate
  cleaned = cleaned.replace(
    /^[*#_>`"'\s]*I am KSRTC SCION \(Supply Chain Intelligence & Operational Network\) for Kerala State Road Transport Corporation\.?[*#_>`"'\s]*/i,
    ""
  );

  // 3. Strip any generic AI assistant intro line at start
  cleaned = cleaned.replace(
    /^[*#_>`"'\s]*(?:I am|I'm|As)\s+(?:an?\s+)?(?:AI\s+assistant|dedicated\s+assistant)[^.\n]*[.:!\n]\s*/i,
    ""
  );

  // 4. Fix accidental duplicate numbering (e.g. 1. Item A ... 1. Item B)
  let listIndex = 0;
  cleaned = cleaned
    .split("\n")
    .map((line) => {
      const match = line.match(/^(\s*)(\d+)\.\s+(.*)/);
      if (match) {
        listIndex += 1;
        return `${match[1]}${listIndex}. ${match[3]}`;
      }
      if (line.trim().startsWith("#") || line.trim() === "---") {
        listIndex = 0;
      }
      return line;
    })
    .join("\n");

  return cleaned.trim() || text.trim();
}

export async function processChatRequest(
  message: string,
  context?: string
): Promise<{ text?: string; error?: string }> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return {
      error:
        "GEMINI_API_KEY environment variable is missing on the server. Please add GEMINI_API_KEY to your server or Vercel project settings.",
    };
  }

  const promptText = context
    ? `${context}\n\nUser Question: ${message}`
    : `User Question: ${message}`;

  try {
    const result = await callInteractionsApi(apiKey, promptText, SYSTEM_INSTRUCTION);
    if (result.text) {
      result.text = sanitizeResponseText(result.text, message);
    }
    return result;
  } catch (err: any) {
    console.error("SCION API server-side error:", err);
    return {
      error: `SCION AI Error: ${err?.message || "Could not generate response from SCION engine."}`,
    };
  }
}
